### ISSUE TITLE
Import Issue

### ISSUE THREAD

**Issue by qguv** [phf/go-openal#1]
After `import "github.com/phf/go-openal/al"`, I get this:

```
# github.com/phf/go-openal/al
buffer.go:9:10: fatal error: 'AL/al.h' file not found
#include <AL/al.h>
         ^
1 error generated.
```

My specs:
- Mac OS 10.8.5 using clang

I believe the file on OS X is `OpenAL/al.h`.

**Comment by dextercai** [comment]
this problem also be reported on Win10.
